# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a1fa36dc14ec21f016384e203eb338d73264b425f7f2bc92be8cdf6e11a5fa7f6f499e5824a7bdbee37026f17c56cb7fdf8461e0d6e387eadde8387f2d1d98

test:
  secret_key_base: 9c48112ccd119e6576d6b4a8e0717502fae8b9c65d4e7dfee0ef4999e21f3f31be337e5e4a461f843c7610fbcf4992c5fab831a8215cb7e2eced1ce01a9a5db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
